version: "3"
services:
  employee-jdbc:
    image: employee-jdbc
    ports:
      - "8080:8080"
    networks:
      - employee-mysql
    depends_on:
      - bootdb
 
  bootdb:
    image: mysql:8.0.28
    networks:
      - employee-mysql
    environment:
      - MYSQL_ALLOW_EMPTY_PASSWORD=True
      - MYSQL_DATABASE=bootdb  
  rapp:
    image: rapp
    ports:
      - "3000:3000"
    networks:
      - employee-mysql
    depends_on:
      - employee-jdbc


networks:
  employee-mysql: